console.log(11111)
console.log(22222)
setTimeout(() => console.log("i working to acyncronous way"), 3000)
fetch('https://jsonplaceholder.typicode.com/todos/1')
    .then(response => response.json())
    .then(json => console.log(json))
console.log(333333)
console.log(44444)
